### PR TITLE
Eliminate Characteristic warnings in console log

### PR DESCRIPTION
**Pull request by tsfischer**
Fixes Issue #186

### CODE REVIEW

**Comment by ronluna** [comment]
What would be the best way to fix sensor.js ?

`
[H Demo Screen@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[NOC Motion Sensor  (#6)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[NOC Motion Sensor  (#6)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[Aeotec Temperature (#6)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[Aeotec Luminiscence (#6)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[Aeotec Luminiscence (#6)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[Aeotec Humidity (#6)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[Aeotec Humidity (#6)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[Hall Motion Sensor  (#11)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[Hall Motion Sensor  (#11)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
[Aeotec Temperature (#11)@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
`

**Comment by tsfischer** [comment]
I don't have any sensors but I do get some of those with dimmers as well. I wasn't as concerned about them since they only happen once upon startup, whereas the others were showing up every time the light was toggled or dimmed. I think we'd need to go through all the device files again and add logic to only set the model on the characteristic if it isn't blank, and if it is blank set it to something such as "Generic Device" or "<unknown model>"?

**Comment by tsfischer** [comment]
Looks like HAP-NodeJS uses "Default-Model" if unspecified, so this plugin should probably just only set another value if it is not empty and not worry about setting something else. Or I suppose we could set it to a type-based model (e.g. "Default-Sensor"

**Comment by ronluna** [comment]
I'm currently doing the following to bypass this warning: 
sensor.js on line 194 

`
            if (isNaN(value)) return;
            if (value !== service.getCharacteristic(characteristic).value){
              //service.setCharacteristic(characteristic,value);
                if (serviceMap.name == "LightSensor" &&  value == 0){
                        console.log("Light Sensor", serviceMap.name, device.name, value)
                        service.setCharacteristic(characteristic,value + 1);
                }else{
                        console.log("Other Sensor", serviceMap.name, device.name, value)
                        service.setCharacteristic(characteristic,value);
                }
            }
`

Seems to be working fine.

**Pull request merged**
