### PR TITLE
adds support for mios garage app and mapps it to the HomeKit Garage type

### PR DESCRIPTION
**Pull request by drewcovi**

### CODE REVIEW

**Comment by drewcovi** [comment]
@damianxd this includes some readmes and a config change as it's not a standard garage opener category for Vera.

**Comment by funstuff234** [comment]
Just tried this, and I got this error in my Homebridge log:

`Unhandled rejection TypeError: Cannot read property 'indexOf' of undefined
    at Object.module.newDevice (/usr/lib/node_modules/homebridge-vera/lib/types/lock.js:36:48)
    at /usr/lib/node_modules/homebridge-vera/lib/functions.js:234:49
    at Array.forEach (native)
    at Object.module.processdevices (/usr/lib/node_modules/homebridge-vera/lib/functions.js:175:16)
    at Object.module.processall (/usr/lib/node_modules/homebridge-vera/lib/functions.js:63:32)
    at /usr/lib/node_modules/homebridge-vera/index.js:57:42
    at tryCatcher (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)`

**Comment by funstuff234** [comment]
Is this stuff even tested before its merged? In the lock.js file, it references a config._garageLocks_ while the documentation is written as _garageLock_. Also, it throws an error if garageLocks isn't specified in the config file.

**Comment by bitmerchandise** [comment]
Thanks for testing funstuff234 and thanks for fixing, if you do!

**Comment by drewcovi** [comment]
@funstuff234 apologies if you see a documentation bug. And thanks for fixing it. The only mechanism we have for testing right now are manual tests around my home. Would love an automated workflow.

**Comment by drewcovi** [comment]
@funstuff234, submitted a quick PR #86

**Comment by djrobx** [comment]
Yeah, keep in mind that this app is challenging to test, as I doubt any of the contributors have all of the device types it supports in their automation setup.    I think we want to err on the side of encouraging people to contribute changes, even if that means things might break once in a while.    

It might be a good idea to branch off relatively "stable" versions for the general public when we feel things are in a good place though.

**Comment by drewcovi** [comment]
Well I have them all ;) but I'm an automation nut.

**Comment by funstuff234** [comment]
@djrobx @drewcovi Yea I definitely agree, my bad for coming off rude. Been looking for a way for my garage door to show up as one in Homekit, so I definitely appreciate this.

**Pull request merged**
