### PR TITLE
Real-time security sensor state polling

### PR DESCRIPTION
**Pull request by damianromanowski**
I found it useful to see my sensors as they trip/untrip, without having to refresh my app. Poll interval is currently hardcoded at 2000ms, but could be added to the config to let the user change it.

### CODE REVIEW

**Comment by damianromanowski** [comment]
Added configurable poll interval. b8df52b4bf296fbcf299a633703f63f9d0b835cb

**Comment by dustindclark** [comment]
@damianxd, any concerns with this PR?  Would like to see it merged and published  Thanks.

**Comment by damianromanowski** [comment]
@dustindclark You can implement this yourself.

* Replace `homebridge-vera/index.js` with: [index.js](https://raw.githubusercontent.com/damianromanowski/homebridge-vera/master/index.js)
* Replace `homebridge-vera/lib/types/securitysense.js` with [securitysense.js](https://raw.githubusercontent.com/damianromanowski/homebridge-vera/master/lib/types/securitysense.js)

Who knows how long it'll be before its merged. I've contributed to projects before and the author went MIA only to merge my changes like 5 months later.

**Comment by dustindclark** [comment]
I saw the change in the diff...pretty straightforward.  I just don't want to run from a fork if possible.  My PR was merged next day, so I think @damianxd is pretty responsive.

**Comment by tsviper** [comment]
Any reason why we can't do this with other devices like switches, thermostats etc?  The HomeKit automations depend on state changes and they are only updated when the app is opened.

**Comment by drewcovi** [comment]
We do. The cache is refreshed 1/second. Many devices check that cache on a regular basis. Can't speak for all of them. But the infrastructure is in place.

**Comment by tsviper** [comment]
That's great. How would I turn it on for the light switches, thermostats, and alarm modes?  The only things that refresh while the app is open are my contact and motion sensors. For instants when I arm my alarm using Vera I do t get a HomeKit  notification until I open the home app.

**Comment by tsviper** [comment]
When I have the Home app open I can see the changes in my contact and motion sensors "live".  However non of my other devices (switches, thermostats, home mode) update unless I go to the home screen then open the Home app again.  It would be great if they refreshed in the app the way the sensors do.  Am I missing something?

**Comment by drewcovi** [comment]
Can't be sure. But I definitely get push notifications from my door/window sensors if notifications are activated. But it was getting annoying so I turned them off a bit ago. I can check and let you know. Can you verify which version you have installed?

**Comment by tsviper** [comment]
I'm running the latest version from here "0.7.6".  I get push notifications from my door/window sensors or motion sensors just fine as well.  However if I setup an automation in the iOS Home app using a light switch as a trigger it will not work.  It will only trigger once I open the Home app.  Hope that makes sense.

**Comment by tsviper** [comment]
It seems that only the security sensors are being polled every few seconds but all other devices are only polled when the Home app is opened.

**Comment by stibbzy** [comment]
Hello. I have exactly the same issue. The only devices that auto-update status while the app is open is security sensors. For all other devices, I have to de-focus the Home App (i.e. go to the iOS home screen or another app), then re-enter the Home App before the device state is reflected in its icon. Is this a limitation of the plugin, because I share it worked as expected a few months ago...

**Comment by stibbzy** [comment]
To add to my comment above, I now see that the dimmer module actually had a section of code to  keep polling the device so that it live-updated in the Home app.

I've adapted that code into the Switch and Temp Sense modules and it seems to be working for those devices now as well. I've had no real coding experience, so I may have modified the files incorrectly, but if anyone is interested, let me know and I can send the files for you to try.

**Comment by drewcovi** [comment]
Yes, I rolled that out as a test and it definitely seemed to work. If that’s working for you, we can roll out checkcharacteristic globally.

**Comment by stibbzy** [comment]
Hi Drew. It seems to be ok to me with my modifications. Did you want my Temp Sense and Switch modules, or will you roll it out globally?

FYI, I left the polling interval at 1000ms, I don’t know if that’s appropriate.

**Comment by drewcovi** [comment]
I can pull myself away from dadding for this ask :) thats why ive been out of pocket these past few years...

**Pull request merged**
