### PR TITLE
Add Support for Vera Security Sensors

### LINKED ISSUE #9: Add Support for Vera Security Sensors

### PR DESCRIPTION
**Pull request by dustindclark**
Fixes #9.

### CODE REVIEW

**Comment by damianromanowski** [comment]
Nice, I was about to ask about security sensor support. In vera security sensors have 6 sub categories:
````
1	Door Sensor
2	Leak Sensor
3	Motion Sensor
4	Smoke Sensor
5	CO Sensor
6	Glass Break Sensor
````

Are there homekit equivalents for these devices? Judging by the code, it simple reports that a sensor has tripped. Whether it be a door/motion/or smoke sensor. Not sure if it needs to be distinguishable. I will merge this tonight to my setup and see how it plays out.

**Comment by damianromanowski** [comment]
Notification Settings - HomeKit

Judging from the above screenshot, Security, Door and Window sensors have their own respective notification schemas. Would be nice to distinguish them as they get added by checking `device.sub_category` in [functions.js](https://github.com/damianxd/homebridge-vera/blob/master/lib/functions.js#L125). Example:

````javascript
    case 4: // Security Sensor
        switch (device.sub_category)
        {
            case 1:
                var DoorSecuritySensor = require("./types/doorsecuritysense.js")(HAPnode,config,module);
                accessories.push(DoorSecuritySensor.newDevice(device));
                break;

            default:
                var SecuritySensor = require("./types/securitysense.js")(HAPnode,config,module);
                accessories.push(SecuritySensor.newDevice(device));
                break;
        }

        HAPnode.debug('------ Security Sensor Added: %s', device.name);
        break;
````

Obviously the code above is just an example and will require additional types under `/lib/types/`

Seems that the 1.7.228 firmware update for Vera UI7 also added window/door sensor (sub?)category as well:
> UI7: 1.7.228 Beta Release version 1.7.228 - Jun 6, 2014 - Beta 2
> Fixed : Different name for category type for a door/window sensor

I wish I had more experience with nodejs and the homekit framework to implement this myself and just do a pull request.

**Comment by dustindclark** [comment]
@damianromanowski , I would encourage you to take stab at it...I'm a web developer, but I only have about a week of NodeJS experience.

As best I can tell, Homebridge has a limitation in that it can only pull information from or push a command to your devices.  It doesn't allow for your devices to push a notification/alert directly from your device to home kit.  This may just be a lack of knowledge on my part, but I haven't seen an example in any plugins yet.

I wasn't aware of security sensor subcategories in Vera (I only have 2 contact sensors on doors).  I'm not sure how the behavior would be different though.  I mapped this to the Homebridge contact sensor.  According to the Vera docs, the security sensor only had 3 variables (Tripped, Armed, and LastTripped)  and the mapping looks something like this:

Vera | Hombridge
------------ | -------------
Security Sensor | ContactSensor
Security Sensor Tripped | Contact - No Contact
Security Sensor Not Tripped | Contact - Contact
Security Sensor Armed | Custom Variable for Armed

Additionally, the current battery level is shown.  So, basically, it's only good for seeing the current status (open/closed, battery level) and for arming/disarming the device.  Any notifications/alerts would be handled by Vera.

I hope I'm missing something and that there's a more useful implementation...so hopefully someone will chime in if that's the case.

**Comment by dustindclark** [comment]
Here's a screenshot of one of my devices.  It seems there's a bug in
homebridge with custom characteristics (Custom = Armed here).  My Nest has
the same problem with the "Away" characteristic.



[image: image1.jpeg]

Dustin

Sent from my iPhone

On Jan 18, 2016, at 1:50 PM, Damian Romanowski <notifications@github.com>
wrote:

[image: Notification Settings - HomeKit]
<https://cloud.githubusercontent.com/assets/5643675/12400645/599599ce-bdef-11e5-917d-474c3168a374.jpg>

Judging from the above screenshot, Security, Door and Window sensors have
their own respective notification schemas. Would be nice to distinguish
them as they get added by checking device.sub_category in functions.js
<https://github.com/damianxd/homebridge-vera/blob/master/lib/functions.js#L125>.
Example:

    case 4: // Security Sensor
        switch (device.sub_category)
        {
            case 1:
                var DoorSecuritySensor =
require("./types/doorsecuritysense.js")(HAPnode,config,module);
                accessories.push(DoorSecuritySensor.newDevice(device));
                break;

            default:
                var SecuritySensor =
require("./types/securitysense.js")(HAPnode,config,module);
                accessories.push(SecuritySensor.newDevice(device));
                break;
        }

        HAPnode.debug('------ Security Sensor Added: %s', device.name);
        break;

Obviously the code above is just an example and will require additional
types under /lib/types/

Seems that the 1.7.228 firmware update for Vera UI7 also added window/door
sensor (sub?)category as well:

UI7: 1.7.228 Beta Release version 1.7.228 - Jun 6, 2014 - Beta 2
Fixed : Different name for category type for a door/window sensor

I wish I had more experience with nodejs and the homekit framework to
implement this myself and just do a pull request.

—
Reply to this email directly or view it on GitHub
<https://github.com/damianxd/homebridge-vera/pull/10#issuecomment-172633621>
.

**Comment by damianromanowski** [comment]
@dustindclark I got a motorized z-wave door lock, and whenever I lock/unlock the door via siri commands, homekit sends a push notification to my device that the door was either locked or unlocked. I imagine the same scenario happens when a security sensor is tripped.

I'm going to take a stab at it right now and see if I can get something working. I'll model it on your existing code. If all goes well I'll be implementing separate door/window/motion security devices for this plugin.

I already looked into some of the code for homebridge and it seems that the prerequisites are there, just needs to be implemented here.

**Comment by dustindclark** [comment]
Right...if the action is initiated with HomeKit, the triggers work fine.
I'm notified as well when my locks are unlocked, but that seems pointless
considering the fact that I told Siri to do so.  What I'm saying is that I
don't think there's a way to be notified when, for example, your window is
opened when you're away from home.  Another example (and one that I would
really like) is that I'd like the lights to turn off when I arm my alarm
from the keypad.  This does not appear to be possible at the moment.

Dustin

Sent from my iPhone

On Jan 18, 2016, at 4:26 PM, Damian Romanowski <notifications@github.com>
wrote:

@dustindclark <https://github.com/dustindclark> I got a motorized z-wave
door lock, and whenever I lock/unlock the door via siri commands, homekit
sends a push notification to my device that the door was either locked or
unlocked. I imagine the same scenario happens when a security sensor is
tripped.

I'm going to take a stab at it right now and see if I can get something
working. I'll model it on your existing code. If all goes well I'll be
implementing separate door/window/motion security devices for this plugin.

I already looked into some of the code for homebridge and it seems that the
prerequisites are there, just needs to be implemented here.

—
Reply to this email directly or view it on GitHub
<https://github.com/damianxd/homebridge-vera/pull/10#issuecomment-172670417>
.

**Comment by damianromanowski** [comment]
@dustindclark Hmm you are absolutely right. I just spent like 3 hours screwing around with it. One thing I managed to do is to update the sensor state when it is tripped from vera. Just uses a simple timer to poll SecuritySensor.getIsTripped(). iDevices updates the state accordingly whether my door sensors are open or closed in real time, not just on first launch. I'll put up a pull request, maybe others will find that useful too.

**Pull request merged**
