### PR TITLE
Some bug fixes

### PR DESCRIPTION
**Pull request by djrobx**
Hi,

I have some bugfixes to contribute:

1) Improved dimmer handling.   There was some code intended to handle overlapping update requests, but it was not written quite right - the "inproc" variable was being cleared after starting the asynchronous HTTP request so it had no effect.    So instead moved this into the HTTP response callback code.   Also changed  "on" states to just send dimming levels, as Vera treats On = 100% bright.   I also ignore attempts to set the On state if its already on (to avoid unwanted brightness requests). 

2) Fix status updates for locks, light,  fan and dimmer so they don't go to "off" when Vera goes offline.    Stops unwanted notifications.

3) Fan was broken.   Update Fan with new dimmer code.

I noticed in several places, there are asynchronous HTTP request callbacks that try to use something in "this".   "this" will not be the same as the local scope, you have to assign it to another variable (like "self") if you want to access them within the callback function.    I knocked a few out, but there are probably some others.

### CODE REVIEW

**Comment by damianxd** [comment]
crap, I did a merge with drewcovi just now and this seems to have conflicts with it

**Comment by drewcovi** [comment]
My update was pretty high-impact, @djrobx. Not sure these bug fixes all still apply.  Might need a quick sync with master, please make sure all `GET` requests no longer make their own independent api requests, but rather use the getVariable method in functions.

**Comment by djrobx** [comment]
Hi Drew, 

Your change fixes the lock polling bug (invalidates my update there), but is otherwise completely complimentary to the dimmer and fan level setting fixes I made.    The important change here is to setBrightness / setRotationSpeed which you did not alter.  

I merged our code together and it's working great!

**Comment by djrobx** [comment]
I'll pull from Master and re-commit and submit anther pull request to make it simpler to see what's needed.

**Comment by djrobx** [comment]
Please just close this request and use #69 instead, as I have resolved the conflicts with Drew's merge.

**Pull request closed without merging**
