### PR TITLE
Use an async http library to make requests

### LINKED ISSUE #19: slooow
Im running this as a plugin with homebridge and it takes anywhere between tens of seconds to minutes to actually apply a change (switch something on/off) Any idea why this may be?

thanks

### PR DESCRIPTION
**Pull request by rcloran**
Instead of using sync-request for http requests, use then-request, and avoid blocking the reactor.

This fixes #19 for me.

### CODE REVIEW

**Comment by rcloran** [comment]
I can't get standalone working, either before or after making these changes, so I'm unable to verify that my changes in VeraLink.js work.

**Comment by damianxd** [comment]
I'm currently working on a new version with request-promise which should fix it

**Comment by rcloran** [comment]
Cool - any idea on a timeline, or can you share your branch? I have some fixes for other issues (which I haven't submitted yet because they stack on top of this, and PRs in github don't stack properly), and I'd be happy to put them on top of your work instead.

**Comment by damianxd** [comment]
It is live now

**Comment by Hackworth** [comment]
Closing this since it was implemented with request-promise

**Pull request closed without merging**
